Repository sp-nitech/diffsptk, pull requests merged in 2024-10, with the labels that each got.

#101 Support batch input in pca
  Makefile
  diffsptk/functional.py
  diffsptk/misc/utils.py
  diffsptk/modules/__init__.py
  diffsptk/modules/cdist.py
  diffsptk/modules/gmm.py
  diffsptk/modules/lbg.py
  diffsptk/modules/pca.py
  diffsptk/modules/rmse.py
  diffsptk/modules/ssim.py
  docs/modules/ssim.rst
  pyproject.toml
  tests/test_pca.py
  tests/test_ssim.py
Labels: enhancement

#104 Minor fix
  .github/workflows/ci.yml
  README.md
  diffsptk/modules/mglsadf.py
Labels: maintenance

#105 bug: TypeError in unsupported operand type(s) for ** or pow(): `numpy.ndarray` and `Tensor`
  diffsptk/misc/utils.py
Labels: bug

#106 Fix sawtooth generation
  diffsptk/functional.py
  diffsptk/modules/excite.py
  tests/test_excite.py
Labels: enhancement
